version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yotam
      MYSQL_DATABASE: web_users
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 32000:3306
