version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - web_project_redis_data:/data
volumes:
  web_project_redis_data:

