version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yotam
    ports:
      - '3306:3306'
    volumes:
      - web_project_mysql_data:/var/lib/mysql
volumes:
  web_project_mysql_data:




