version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    links:
      - db1
      - db2

  db1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'yotam'
      MYSQL_DATABASE: 'web_users'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306"]
      interval: 10s
      timeout: 5s
      retries: 3

  db2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'yotam'
      MYSQL_DATABASE: 'site_entries'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3309:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3307"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  data:
