version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'yotam'
      MYSQL_DATABASE: 'db'
    volumes:
      - data:/var/lib/mysql

volumes:
  data:

#ports:
#  - '3306:3306'
