version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    command: sh -c "sleep 10 && python app.py"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yotam
      MYSQL_DATABASE: web_users
    volumes:
      - data:/var/lib/mysql
volumes:
 data:
    # ports:
    #   - 3306:3306

