version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy  # הוספת תנאי תלות על המסד נתונים
    links:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'yotam'
      MYSQL_DATABASE: 'db'
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:  # הוספת-healthcheck למסד הנתונים
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  data:
