CREATE DATABASE IF NOT EXISTS web_users;

USE web_users;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  username VARCHAR(255) NOT NULL
);
